import type { Certificate, CertificateRecord } from "./types";

/**
 * The Downloads table on the live site (https://sweillem.net/resources/),
 * in its order. Six entries link to "https://eg" (broken) and have no file.
 */
export const certificates: Certificate[] = [
  {
    name: "Cradle to Cradle",
    country: "Global",
    externalUrl: "https://c2ccertified.org/certified-products/vitrified-clay-pipe-dn-125-to-dn-1000-with-accessories",
    status: "external",
    notes:
      "Listed with the C2C registry link in the Description column and no file. A scan named Sweil_Vitri_Bronz_CERT9605_2025-05-06 is in the media library (see assets manifest).",
  },
  {
    name: "ISO 9001",
    country: "Egypt",
    file: "/downloads/certificates/iso-9001-2024.pdf",
    liveUrl: "https://sweillem.net/wp-content/uploads/2025/02/8488-Sweillem-Vitrified-Clay-Pipes-ISO-9001-Certificate-June-2024-signed-sealed.pdf",
    status: "pending-download",
  },
  {
    name: "DIN CERTCO",
    country: "Germany",
    file: "/downloads/certificates/din-certco-2027.pdf",
    liveUrl: "https://sweillem.net/wp-content/uploads/2025/02/DIN-CERTCO31-05-2027-EN.pdf",
    status: "pending-download",
    notes: "File name suggests validity to 31-05-2027.",
  },
  {
    name: "SASO",
    country: "KSA",
    file: "/downloads/certificates/saso-2022-2025.pdf",
    liveUrl: "https://sweillem.net/wp-content/uploads/2025/02/SASO-2022-2025.pdf",
    status: "pending-download",
    notes: "File name says 2022 to 2025; may have expired.",
  },
  { name: "BENOR", country: "Belgium", status: "missing", notes: 'Live link is "https://eg".' },
  { name: "CERTIFIKA'T", country: "Czech Republic", status: "missing", notes: 'Live link is "https://eg".' },
  { name: "NOPWASD", country: "Egypt", status: "missing", notes: 'Live link is "https://eg".' },
  { name: "NF CSTB 108", country: "French", status: "missing", notes: 'Live link is "https://eg".' },
  { name: "NL BSB", country: "Netherlands", status: "missing", notes: 'Live link is "https://eg".' },
  { name: "TUV", country: "Singapore", status: "missing", notes: 'Live link is "https://eg".' },
  {
    name: "ISO 45001: 2024",
    country: "Egypt",
    category: "Safety",
    file: "/downloads/certificates/iso-45001-2024.pdf",
    liveUrl: "https://sweillem.net/wp-content/uploads/2025/02/9720-Sweillem-Vitrified-Clay-Pipes-ISO-45001-Certificate-Apr-2024-signed-sealed.pdf",
    status: "pending-download",
    notes: "About Us lists OHSAS 18001:2007 instead; ask which is current.",
  },
  {
    name: "ISO 14001",
    country: "Egypt",
    category: "Safety",
    file: "/downloads/certificates/iso-14001-2024.pdf",
    liveUrl: "https://sweillem.net/wp-content/uploads/2025/02/8401-Sweillem-Vitrified-Clay-Pipes-ISO-14001-Certificate-Apr-2024-signed-sealed.pdf",
    status: "pending-download",
    notes: 'Labelled "Safety" on the live site; ISO 14001 is an environmental standard.',
  },
];

/** Standards named in the About Us text (not all have a certificate file). */
export const standardsClaimed = [
  "Egyptian Standards (ES 56/2005)",
  "Saudi Standards (SASO GSO EN 295/2008)",
  "European Standards (EN 295)",
  "German standard (ZPWN 295:2016)",
  "American Standards (ASTM-C700)",
  "ISO 9001:2015",
  "ISO 14001:2015",
  "OHSAS 18001:2007",
] as const;

/**
 * The certificates SWEILLEM publishes, transcribed from the files themselves
 * (scans on the live Certificates page and PDFs from Downloads). The live site
 * carries two issues of each ISO certificate: American Systems Registrar (2024,
 * PDF) and OSS Middle East (2025, scan). Both are listed.
 */
export const certificateRecords: CertificateRecord[] = [
  {
    id: "iso-9001-asr",
    standard: "ISO 9001:2015",
    title: "Quality management system",
    issuer: "American Systems Registrar (ANAB accredited)",
    number: "8488",
    scope: "Manufacturer and sales of vitrified clay products",
    issued: "2024-06-07",
    validUntil: "2027-06-06",
    image: "/images/certificates/iso-9001-2015-scan.jpg",
    file: "/downloads/certificates/iso-9001-2024.pdf",
    kind: "management",
    notes: "Initial registration 8 June 2021.",
  },
  {
    id: "iso-9001-oss",
    standard: "ISO 9001:2015",
    title: "Quality management system",
    issuer: "OSS Middle East Certification (EGAC accredited)",
    number: "MSE 0640525A",
    scope: "Manufacturer and sales of vitrified clay products",
    issued: "2025-05-13",
    validUntil: "2026-05-12",
    image: "/images/certificates/iso-9001.jpg",
    kind: "management",
    notes: "Three-year cycle to 12 May 2028, renewed each year after a surveillance audit.",
  },
  {
    id: "iso-14001-asr",
    standard: "ISO 14001:2015",
    title: "Environmental management system",
    issuer: "American Systems Registrar (ANAB accredited)",
    number: "8401",
    scope: "Manufacturer and sales of vitrified clay products",
    issued: "2024-04-07",
    validUntil: "2027-04-06",
    image: "/images/certificates/iso-14001-asr-2024.webp",
    file: "/downloads/certificates/iso-14001-2024.pdf",
    kind: "management",
    notes: "Initial registration 8 April 2021.",
  },
  {
    id: "iso-14001-oss",
    standard: "ISO 14001:2015",
    title: "Environmental management system",
    issuer: "OSS Middle East Certification (EGAC accredited)",
    number: "MSE 0640525B",
    scope: "Manufacturer and sales of vitrified clay products",
    issued: "2025-05-13",
    validUntil: "2026-05-12",
    image: "/images/certificates/iso-14001.jpg",
    kind: "management",
    notes: "Three-year cycle to 12 May 2028, renewed each year after a surveillance audit.",
  },
  {
    id: "iso-45001-asr",
    standard: "ISO 45001:2018",
    title: "Occupational health and safety management system",
    issuer: "American Systems Registrar (ANAB accredited)",
    number: "9720",
    scope: "Manufacturer and sales of vitrified clay products",
    issued: "2024-04-03",
    validUntil: "2027-04-02",
    image: "/images/certificates/iso-45001-asr-2024.webp",
    file: "/downloads/certificates/iso-45001-2024.pdf",
    kind: "management",
  },
  {
    id: "iso-45001-oss",
    standard: "ISO 45001:2018",
    title: "Occupational health and safety management system",
    issuer: "OSS Middle East Certification (EGAC accredited)",
    number: "MSE 0640525C",
    scope: "Manufacturer and sales of vitrified clay products",
    issued: "2025-05-13",
    validUntil: "2026-05-12",
    image: "/images/certificates/iso-45001.jpg",
    kind: "management",
    notes: "Three-year cycle to 12 May 2028, renewed each year after a surveillance audit.",
  },
  {
    id: "din-certco",
    standard: "DIN plus, EN 295-1 and EN 295-4",
    title: "Joint seals for glazed vitrified clay pipes",
    issuer: "DIN CERTCO (DAkkS accredited)",
    number: "P1S048",
    scope: "Seals, tested to EN 295-1:2013, EN 295-4:2013 and certification scheme WN 295 (2016-01). Production facility: Sriaqos, Khanka City",
    issued: "2022-04-04",
    validUntil: "2027-05-31",
    image: "/images/certificates/din-certco.jpg",
    file: "/downloads/certificates/din-certco-2027.pdf",
    kind: "product",
  },
  {
    id: "saso",
    standard: "SASO GSO EN 295-1/2008",
    title: "Saudi quality mark licence",
    issuer: "Saudi Standards, Metrology and Quality Organization (SASO)",
    number: "201900003011",
    scope: "Vitrified clay pipes for water and sewage drainage, made at Saryaqos, Qalyubia",
    issued: "2022-06-30",
    validUntil: "2025-06-29",
    image: "/images/certificates/saso.jpg",
    file: "/downloads/certificates/saso-2022-2025.pdf",
    kind: "product",
    notes: "First granted 12 May 2007; this copy is the 2022 renewal.",
  },
  {
    id: "cradle-to-cradle",
    standard: "Cradle to Cradle Certified, Full Scope Bronze (v4.1)",
    title: "Product circularity and material health",
    issuer: "Cradle to Cradle Products Innovation Institute",
    number: "9605",
    scope: "Vitrified Clay Pipe DN 125 to DN 1000 with Accessories",
    issued: "2025-05-06",
    validUntil: "2028-05-05",
    image: "/images/certificates/cradle-to-cradle-bronze-9605.jpg",
    externalUrl: "https://c2ccertified.org/certified-products/vitrified-clay-pipe-dn-125-to-dn-1000-with-accessories",
    kind: "product",
    notes: "Lead assessment body Sustenuto; material health assessment ARCHE Consulting.",
  },
];
